export default Object.freeze({
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
  SET_TOTAL_PAGES: "SET_TOTAL_PAGES",
  SET_PAGE_SIZE: "SET_PAGE_SIZE",
  SET_SORT_BY: "SET_SORT_BY",
  SET_SORT_DIRECTION: "SET_SORT_DIRECTION",
  SET_FILTER_RESULTS: "SET_FILTER_RESULTS",
})
